### ISSUE TITLE
Add %v to examples

### ISSUE THREAD

**Issue by rsharifnasab** [1995parham-teaching/hello-go#3]
IMHO one of the most powerful Go's fmt features is formatting without specifying the type with `%v`. for those people who are not familiar with `stdio`-style formatting, it might be more convenient to use `%v` for formatting all variables, even simple ones like numbers and strings.

Proposed add place: [here](https://github.com/1995parham-teaching/go-lecture/blob/1fbc3c1e76c84b4f92234b1ae8665276a1bbbe0b/01-constants-and-variables/main.go#L34)

**Comment by 1995parham** [comment]
You are completely right. I will add it.
